---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Kibana repository.
  apt_repository:
    repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/{{ kibana_version }}/ stable main'
    state: present
    validate_certs: false
    update_cache: true
